-- SQL script to populate selected_modules for Super Admin account
-- This gives the Super Admin access to all modules and submodules

-- First, find the Super Admin user ID (replace with actual email if needed)
-- UPDATE users 
-- SET selected_modules = '[
--   {"id":"module-Dashboard","label":"Dashboard","module":"Dashboard","isSubmodule":false},
--   {"id":"module-Students","label":"Students","module":"Students","isSubmodule":false},
--   {"id":"submodule-Students-masterlist","label":"Students > Masterlist","module":"Students","isSubmodule":true,"submoduleId":"masterlist"},
--   {"id":"submodule-Students-assessments","label":"Students > Assessments","module":"Students","isSubmodule":true,"submoduleId":"assessments"},
--   {"id":"submodule-Students-disciplinary","label":"Students > Disciplinary","module":"Students","isSubmodule":true,"submoduleId":"disciplinary"},
--   {"id":"submodule-Students-attendance","label":"Students > Attendance","module":"Students","isSubmodule":true,"submoduleId":"attendance"},
--   {"id":"submodule-Students-transport","label":"Students > Transport","module":"Students","isSubmodule":true,"submoduleId":"transport"},
--   {"id":"submodule-Students-boarding","label":"Students > Boarding","module":"Students","isSubmodule":true,"submoduleId":"boarding"},
--   {"id":"submodule-Students-medical","label":"Students > Medical","module":"Students","isSubmodule":true,"submoduleId":"medical"},
--   {"id":"module-Financials","label":"Financials","module":"Financials","isSubmodule":false},
--   {"id":"submodule-Financials-overview","label":"Financials > Overview","module":"Financials","isSubmodule":true,"submoduleId":"overview"},
--   {"id":"submodule-Financials-invoices","label":"Financials > Invoices","module":"Financials","isSubmodule":true,"submoduleId":"invoices"},
--   {"id":"submodule-Financials-fee-structure","label":"Financials > Fee Structure","module":"Financials","isSubmodule":true,"submoduleId":"fee-structure"},
--   {"id":"submodule-Financials-payments","label":"Financials > Received","module":"Financials","isSubmodule":true,"submoduleId":"payments"},
--   {"id":"submodule-Financials-expenses","label":"Financials > Expenses","module":"Financials","isSubmodule":true,"submoduleId":"expenses"},
--   {"id":"submodule-Financials-payroll","label":"Financials > Payroll","module":"Financials","isSubmodule":true,"submoduleId":"payroll"},
--   {"id":"module-Procurement","label":"Procurement","module":"Procurement","isSubmodule":false},
--   {"id":"submodule-Procurement-inventory","label":"Procurement > Inventory","module":"Procurement","isSubmodule":true,"submoduleId":"inventory"},
--   {"id":"submodule-Procurement-requisitions","label":"Procurement > Requisitions","module":"Procurement","isSubmodule":true,"submoduleId":"requisitions"},
--   {"id":"submodule-Procurement-repair-requests","label":"Procurement > Repair Requests","module":"Procurement","isSubmodule":true,"submoduleId":"repair-requests"},
--   {"id":"submodule-Procurement-asset-issuance","label":"Procurement > Asset Issuance","module":"Procurement","isSubmodule":true,"submoduleId":"asset-issuance"},
--   {"id":"submodule-Procurement-budgets","label":"Procurement > Budgets","module":"Procurement","isSubmodule":true,"submoduleId":"budgets"},
--   {"id":"module-HR","label":"HR","module":"HR","isSubmodule":false},
--   {"id":"submodule-HR-staff-info","label":"HR > Staff Info","module":"HR","isSubmodule":true,"submoduleId":"staff-info"},
--   {"id":"submodule-HR-leave","label":"HR > Leave","module":"HR","isSubmodule":true,"submoduleId":"leave"},
--   {"id":"submodule-HR-disciplinary","label":"HR > Disciplinary","module":"HR","isSubmodule":true,"submoduleId":"disciplinary"},
--   {"id":"submodule-HR-performance","label":"HR > Performance","module":"HR","isSubmodule":true,"submoduleId":"performance"},
--   {"id":"module-Programs","label":"Programs","module":"Programs","isSubmodule":false},
--   {"id":"submodule-Programs-school-calendar","label":"Programs > School Calendar","module":"Programs","isSubmodule":true,"submoduleId":"school-calendar"},
--   {"id":"submodule-Programs-lesson-plans","label":"Programs > Lesson Plans","module":"Programs","isSubmodule":true,"submoduleId":"lesson-plans"},
--   {"id":"submodule-Programs-shifts","label":"Programs > Shifts","module":"Programs","isSubmodule":true,"submoduleId":"shifts"},
--   {"id":"submodule-Programs-schedules","label":"Programs > Schedules","module":"Programs","isSubmodule":true,"submoduleId":"schedules"},
--   {"id":"module-Library","label":"Library","module":"Library","isSubmodule":false},
--   {"id":"submodule-Library-books-masterlist","label":"Library > Books Masterlist","module":"Library","isSubmodule":true,"submoduleId":"books-masterlist"},
--   {"id":"submodule-Library-borrowing-records","label":"Library > Borrowing Records","module":"Library","isSubmodule":true,"submoduleId":"borrowing-records"},
--   {"id":"module-Tasks","label":"Tasks","module":"Tasks","isSubmodule":false},
--   {"id":"module-Custom Records","label":"Custom Records","module":"Custom Records","isSubmodule":false},
--   {"id":"module-Leads","label":"Leads","module":"Leads","isSubmodule":false},
--   {"id":"module-Reports","label":"Reports","module":"Reports","isSubmodule":false},
--   {"id":"module-Settings","label":"Settings","module":"Settings","isSubmodule":false},
--   {"id":"submodule-Settings-user-management","label":"Settings > User Management","module":"Settings","isSubmodule":true,"submoduleId":"user-management"},
--   {"id":"submodule-Settings-import-data","label":"Settings > Import Data","module":"Settings","isSubmodule":true,"submoduleId":"import-data"},
--   {"id":"submodule-Settings-export-data","label":"Settings > Export Data","module":"Settings","isSubmodule":true,"submoduleId":"export-data"},
--   {"id":"submodule-Settings-modules","label":"Settings > Modules","module":"Settings","isSubmodule":true,"submoduleId":"modules"},
--   {"id":"submodule-Settings-security","label":"Settings > Security","module":"Settings","isSubmodule":true,"submoduleId":"security"},
--   {"id":"submodule-Settings-activity-log","label":"Settings > Activity Log","module":"Settings","isSubmodule":true,"submoduleId":"activity-log"}
-- ]'::jsonb
-- WHERE role = 'Super Admin' OR role = 'Superadmin';

-- Alternative: Update by email (replace with actual Super Admin email)
UPDATE users 
SET selected_modules = '[
  {"id":"module-Dashboard","label":"Dashboard","module":"Dashboard","isSubmodule":false},
  {"id":"module-Students","label":"Students","module":"Students","isSubmodule":false},
  {"id":"submodule-Students-masterlist","label":"Students > Masterlist","module":"Students","isSubmodule":true,"submoduleId":"masterlist"},
  {"id":"submodule-Students-assessments","label":"Students > Assessments","module":"Students","isSubmodule":true,"submoduleId":"assessments"},
  {"id":"submodule-Students-disciplinary","label":"Students > Disciplinary","module":"Students","isSubmodule":true,"submoduleId":"disciplinary"},
  {"id":"submodule-Students-attendance","label":"Students > Attendance","module":"Students","isSubmodule":true,"submoduleId":"attendance"},
  {"id":"submodule-Students-transport","label":"Students > Transport","module":"Students","isSubmodule":true,"submoduleId":"transport"},
  {"id":"submodule-Students-boarding","label":"Students > Boarding","module":"Students","isSubmodule":true,"submoduleId":"boarding"},
  {"id":"submodule-Students-medical","label":"Students > Medical","module":"Students","isSubmodule":true,"submoduleId":"medical"},
  {"id":"module-Financials","label":"Financials","module":"Financials","isSubmodule":false},
  {"id":"submodule-Financials-overview","label":"Financials > Overview","module":"Financials","isSubmodule":true,"submoduleId":"overview"},
  {"id":"submodule-Financials-invoices","label":"Financials > Invoices","module":"Financials","isSubmodule":true,"submoduleId":"invoices"},
  {"id":"submodule-Financials-fee-structure","label":"Financials > Fee Structure","module":"Financials","isSubmodule":true,"submoduleId":"fee-structure"},
  {"id":"submodule-Financials-payments","label":"Financials > Received","module":"Financials","isSubmodule":true,"submoduleId":"payments"},
  {"id":"submodule-Financials-expenses","label":"Financials > Expenses","module":"Financials","isSubmodule":true,"submoduleId":"expenses"},
  {"id":"submodule-Financials-payroll","label":"Financials > Payroll","module":"Financials","isSubmodule":true,"submoduleId":"payroll"},
  {"id":"module-Procurement","label":"Procurement","module":"Procurement","isSubmodule":false},
  {"id":"submodule-Procurement-inventory","label":"Procurement > Inventory","module":"Procurement","isSubmodule":true,"submoduleId":"inventory"},
  {"id":"submodule-Procurement-requisitions","label":"Procurement > Requisitions","module":"Procurement","isSubmodule":true,"submoduleId":"requisitions"},
  {"id":"submodule-Procurement-repair-requests","label":"Procurement > Repair Requests","module":"Procurement","isSubmodule":true,"submoduleId":"repair-requests"},
  {"id":"submodule-Procurement-asset-issuance","label":"Procurement > Asset Issuance","module":"Procurement","isSubmodule":true,"submoduleId":"asset-issuance"},
  {"id":"submodule-Procurement-budgets","label":"Procurement > Budgets","module":"Procurement","isSubmodule":true,"submoduleId":"budgets"},
  {"id":"module-HR","label":"HR","module":"HR","isSubmodule":false},
  {"id":"submodule-HR-staff-info","label":"HR > Staff Info","module":"HR","isSubmodule":true,"submoduleId":"staff-info"},
  {"id":"submodule-HR-leave","label":"HR > Leave","module":"HR","isSubmodule":true,"submoduleId":"leave"},
  {"id":"submodule-HR-disciplinary","label":"HR > Disciplinary","module":"HR","isSubmodule":true,"submoduleId":"disciplinary"},
  {"id":"submodule-HR-performance","label":"HR > Performance","module":"HR","isSubmodule":true,"submoduleId":"performance"},
  {"id":"module-Programs","label":"Programs","module":"Programs","isSubmodule":false},
  {"id":"submodule-Programs-school-calendar","label":"Programs > School Calendar","module":"Programs","isSubmodule":true,"submoduleId":"school-calendar"},
  {"id":"submodule-Programs-lesson-plans","label":"Programs > Lesson Plans","module":"Programs","isSubmodule":true,"submoduleId":"lesson-plans"},
  {"id":"submodule-Programs-shifts","label":"Programs > Shifts","module":"Programs","isSubmodule":true,"submoduleId":"shifts"},
  {"id":"submodule-Programs-schedules","label":"Programs > Schedules","module":"Programs","isSubmodule":true,"submoduleId":"schedules"},
  {"id":"module-Library","label":"Library","module":"Library","isSubmodule":false},
  {"id":"submodule-Library-books-masterlist","label":"Library > Books Masterlist","module":"Library","isSubmodule":true,"submoduleId":"books-masterlist"},
  {"id":"submodule-Library-borrowing-records","label":"Library > Borrowing Records","module":"Library","isSubmodule":true,"submoduleId":"borrowing-records"},
  {"id":"module-Tasks","label":"Tasks","module":"Tasks","isSubmodule":false},
  {"id":"module-Custom Records","label":"Custom Records","module":"Custom Records","isSubmodule":false},
  {"id":"module-Leads","label":"Leads","module":"Leads","isSubmodule":false},
  {"id":"module-Reports","label":"Reports","module":"Reports","isSubmodule":false},
  {"id":"module-Settings","label":"Settings","module":"Settings","isSubmodule":false},
  {"id":"submodule-Settings-user-management","label":"Settings > User Management","module":"Settings","isSubmodule":true,"submoduleId":"user-management"},
  {"id":"submodule-Settings-import-data","label":"Settings > Import Data","module":"Settings","isSubmodule":true,"submoduleId":"import-data"},
  {"id":"submodule-Settings-export-data","label":"Settings > Export Data","module":"Settings","isSubmodule":true,"submoduleId":"export-data"},
  {"id":"submodule-Settings-modules","label":"Settings > Modules","module":"Settings","isSubmodule":true,"submoduleId":"modules"},
  {"id":"submodule-Settings-security","label":"Settings > Security","module":"Settings","isSubmodule":true,"submoduleId":"security"},
  {"id":"submodule-Settings-activity-log","label":"Settings > Activity Log","module":"Settings","isSubmodule":true,"submoduleId":"activity-log"}
]'::jsonb
WHERE role = 'Super Admin' OR role = 'Superadmin';

