// src/types/database.ts (READY TO PASTE)

// ----------------------------------------------------------------------
// --- 1. Base Interfaces ---
// ----------------------------------------------------------------------

// Required NEW TYPE for Student Search/Autocomplete
export interface StudentInfo {
    admission_number: string;
    name: string;
    // FIX: Added class_name to support student grouping and display in the batch invoice component.
    class_name: string | null; 
    // Add other relevant student fields if needed, e.g., class_id, etc.
}

// Item Master Interface (for the inventory of services/products)
export interface ItemMaster {
    id: string; // uuid
    created_at: string; // timestamp
    item_name: string;
    current_unit_price: number; // numeric(10, 2)
    description: string | null; // text | nullable
}

// ----------------------------------------------------------------------
// --- 2. Core Invoice Components (Switched to CamelCase for client-side consistency) ---
// ----------------------------------------------------------------------

// Invoice Line Item Interface - Represents a single item on an invoice.
export interface InvoiceLineItem {
    // Unique fields from DB (optional for new submissions)
    id?: string; // uuid (Generated by DB)
    created_at?: string; // timestamp (Generated by DB)
    invoice_number?: string; // text (Foreign Key - set during DB insertion)
    
    // Foreign Key
    item_master_id: string; // uuid (Foreign Key to item_master)
    
    // NEW FIELD (Added and named in camelCase for consistency)
    itemName: string; // The name at the time of billing

    // Input fields (Changed from snake_case to camelCase to fix the error)
    description: string | null; // text (Can be overridden from ItemMaster)
    unitPrice: number; // numeric (Price at time of billing) <-- FIX: changed from unit_price
    quantity: number; // integer
    discount: number; // numeric (Stored as percentage, e.g., 5 for 5%)
    
    // Calculated field (Changed from snake_case to camelCase)
    lineTotal: number; // numeric (unitPrice * quantity * (1 - discount/100)) <-- FIX: changed from line_total
}

// Invoice Header Interface - Represents the main invoice record.
export interface InvoiceHeader {
    // Generated by Trigger/DB
    invoice_number: string; // text (Primary Key)
    invoice_seq_number: number | null; // integer | nullable
    created_at: string; // timestamp
    
    // Header Input Fields (Form)
    admission_number: string; // text
    name: string; // text
    // --- ADDED PROP: Sourced from student join in service ---
    class_name: string | null; 
    // --------------------------------------------------------
    invoice_date: string; // date (YYYY-MM-DD format)
    due_date: string; // date (YYYY-MM-DD format)
    status: 'Draft' | 'Pending' | 'Paid' | 'Overdue'; // text
    description: string | null; // text (The general description, e.g., 'Q1 Term Fees')

    // Balance Brought Forward Fields
    broughtforward_description: string | null; // text | nullable
    broughtforward_amount: number | null; // numeric | nullable
    
    // Calculated/DB-managed fields (Changed from snake_case to camelCase)
    subtotal: number; // numeric (Line Items sum, excluding B/F)
    totalAmount: number; // numeric (subtotal + broughtforward_amount - total_discount) <-- FIX: changed from total_amount
    paymentMade: number; // numeric <-- FIX: changed from payment_made
    balanceDue: number; // numeric (Calculated by trigger: totalAmount - paymentMade) <-- FIX: changed from balance_due
}

// ----------------------------------------------------------------------
// --- 3. Combined & Submission Types ---
// ----------------------------------------------------------------------

// Combined Type for a Full Invoice View (for fetching a single invoice)
export interface FullInvoice extends InvoiceHeader {
    line_items: InvoiceLineItem[];
    // class_name is inherited from InvoiceHeader
}

// Data Submission Type: What the client actually sends to the API for creation/update.
export interface InvoiceSubmissionData {
    // Omit DB-managed fields and the calculated fields that the client is expected to re-calculate/submit
    header: Omit<
        InvoiceHeader, 
        | 'invoice_number' 
        | 'created_at' 
        | 'invoice_seq_number' 
        // --- ADDED OMIT: The UI does not submit the class_name ---
        | 'class_name' 
        // --------------------------------------------------------
        // Omit the calculated fields from the base type so we can explicitly require them below
        | 'subtotal'
        | 'totalAmount' 
        | 'paymentMade' 
        | 'balanceDue' 
    > & {
        // Explicitly require the client to submit the current calculated totals
        subtotal: number;
        totalAmount: number;
        paymentMade: number;
        // balanceDue is now CORRECTLY omitted, as the backend calculates it.
    };
    line_items: InvoiceLineItem[];
}

// ----------------------------------------------------------------------
// --- 4. NEW: Balance Brought Forward Interface ---
// ----------------------------------------------------------------------

/**
 * Interface used to display a preview of outstanding, overdue invoices 
 * before they are transferred and deleted.
 */
export interface OutstandingBalanceReview {
    admission_number: string;
    name: string; // Student name
    invoice_number: string;
    invoice_description: string | null; // The description field from the original invoice
    balance_due: number;
}